/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avengersgameproject;

/**
 *
 * @author Xuqiang
 */
public class CharacterSelect extends javax.swing.JFrame {

    /**
     * Creates new form CharacterSelect
     */
    public CharacterSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AntmanSelect = new javax.swing.JButton();
        AntmanLabel = new javax.swing.JLabel();
        Thor = new javax.swing.JLabel();
        ThorSelect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Avengers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Sitka Banner", 0, 48)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("CHARACTER SELECT");
        getContentPane().add(Title);
        Title.setBounds(90, 50, 458, 100);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avengersgameproject/AntmanSelectResize.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 210, 180, 320);

        AntmanSelect.setBorderPainted(false);
        AntmanSelect.setContentAreaFilled(false);
        AntmanSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntmanSelectActionPerformed(evt);
            }
        });
        getContentPane().add(AntmanSelect);
        AntmanSelect.setBounds(0, 210, 180, 310);

        AntmanLabel.setFont(new java.awt.Font("Segoe WP Black", 0, 24)); // NOI18N
        AntmanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AntmanLabel.setText("ANTMAN");
        getContentPane().add(AntmanLabel);
        AntmanLabel.setBounds(0, 140, 180, 50);

        Thor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Thor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avengersgameproject/ThorResize.png"))); // NOI18N
        getContentPane().add(Thor);
        Thor.setBounds(210, 200, 200, 320);

        ThorSelect.setBorderPainted(false);
        ThorSelect.setContentAreaFilled(false);
        ThorSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThorSelectActionPerformed(evt);
            }
        });
        getContentPane().add(ThorSelect);
        ThorSelect.setBounds(210, 200, 200, 320);

        jLabel1.setFont(new java.awt.Font("Segoe WP Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 140, 190, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avengersgameproject/rsz_duke (1).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 240, 212, 280);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THE AVENGERS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 140, 200, 60);

        Avengers.setBorderPainted(false);
        Avengers.setContentAreaFilled(false);
        Avengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvengersActionPerformed(evt);
            }
        });
        getContentPane().add(Avengers);
        Avengers.setBounds(420, 220, 210, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AntmanSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntmanSelectActionPerformed
        AntmanScreen Antman = new AntmanScreen();
        Antman.setBounds(0, 0, 646, 658);
        Antman.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AntmanSelectActionPerformed

    private void ThorSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThorSelectActionPerformed
        ThorScreen Thor = new ThorScreen();
        Thor.setBounds(0, 0, 646, 658);
        Thor.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ThorSelectActionPerformed

    private void AvengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvengersActionPerformed
        AvengersTeamScreen avengersScreen = new AvengersTeamScreen();
        avengersScreen.setBounds(0, 0, 646, 670);
        avengersScreen.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_AvengersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AntmanLabel;
    private javax.swing.JButton AntmanSelect;
    private javax.swing.JButton Avengers;
    private javax.swing.JLabel Thor;
    private javax.swing.JButton ThorSelect;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
